### ISSUE TITLE
Unit test failures (in BIP-39) when building for Windows.

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-sdk-cpp#136]
### Description

Pursuant to #133 (and using that PR as `HEAD`) built the SDK in _release_ configuration using CMake's Visual Studio 17 2022 Generator.  Got unit test failures, log attached.
:
(N.B: Running `hedera-sdk-cpp-tests` passes all tests.  There's a difference between `ctest` and `hedera-sdk-cpp-tests` ...)

### Steps to reproduce

Having built the SDK per instructions in the README, do `ctest --config Release` and see the failures as in the attached log.

### Additional context

[sdk-ctest-fail.log](https://github.com/hashgraph/hedera-sdk-cpp/files/10212223/sdk-ctest-fail.log)

### Hedera network

testnet

### Version

pre-release SDK

### Operating system

Windows

**Comment by rwalworth** [comment]
Addressed in #138 .
