### ISSUE TITLE
Remove remaining prints on failure

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-sdk-cpp#152]
- There are some instances of `cout` messages indicating failures
- These should be replaced by exceptions

**Comment by deyanzz** [comment]
I found only one usage of `cout` message as a failure.
My changes are introduced in [PR 60](https://github.com/hashgraph/hedera-sdk-cpp/pull/160).

**Comment by deyanzz** [comment]
[PR 160](https://github.com/hashgraph/hedera-sdk-cpp/pull/160) was approved and merged into `main` branch.
