### ISSUE TITLE
Segmentation Fault when calling method `execute()` in `AccountCreateTransaction`

### ISSUE THREAD

**Issue by deyanzz** [hashgraph/hedera-sdk-cpp#192]
### Description

A runtime error is thrown when executing the `CreateAccountExample` with the following input arguments:
Network: `Testnet`
Account Type: `ED25519`
> PrivateKey: HIDDEN
PublicKey: 6c8f67f9bef71291def48364c0e4cfbb14c924b75e7529108efc7197a12b4996
Account ID: 0.0.1359

The same example for `AccountCreateTransaction` was tested in `Go SDK` and it passed successfully - [Hashscan Transaction](https://hashscan.io/testnet/transaction/1675428698.106823003?tid=0.0.1359-1675428686-489922449).

### Steps to reproduce

Please, checkout sample git branch `segmentation-fault-when-calling-execute`.

Then compile & build the `C++ SDK` and all of the examples - follow the steps below.

Run the following commands from terminal:
1. `git submodule update --init`
2. `cmake --preset macos-arm64-debug`
3. `cmake --build --preset macos-arm64-debug`
4. `ctest -C Debug --test-dir build/macos-arm64-debug`

After that execute the following command from terminal:
`./package/Debug/Darwin/arm64/examples/hedera-sdk-cpp-create-account-example 0.0.1359 2e000363977258a41f418cf84a7df9cf1e8ae98b72de86803e64846defa43054`

### Additional context

![Screenshot 2023-02-03 at 16 23 07](https://user-images.githubusercontent.com/4867816/216628065-ec23e391-dec5-4a9f-9853-796735bd24f6.png)
 
![AccountCreateTransaction_SEG_FAULT](https://user-images.githubusercontent.com/4867816/216628173-2b5e58f2-a818-4975-b255-3a543fd4a5f8.png)

### Hedera network

testnet

### Version

v0.1.0

### Operating system

macOS

**Comment by rwalworth** [comment]
@deyanzz have you been able to get more details about this? I haven't been able to reproduce this issue

**Comment by deyanzz** [comment]
> @deyanzz I noticed the remote branch for this issue was deleted. Are you okay with me closing this issue?

That's correct. I deleted the remote feature branch for this issue. In fact I found where was the problem - it's not because of this particular example. I will close the issue now.
