### ISSUE TITLE
Feature parity with the Hedera Java SDK

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-cpp#215]
Problem

As a developer, I want to use Hedera's feature by accessing an APIs supported via the SDK.

Solution

Implement the following features:

**Accounts**
- [x] #241
- [x] #243
- [x] [AccountBalance](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/AccountBalance.java)
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/10
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/12
- [x] #230
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/18
- [x] [AccountInfo](https://github.com/hashgraph/hederasdkjava/blo/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/AccountInfo.java)
- [x] [AccountInfoFlow](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/AccountInfoFlow.java) (cannot find use case, ignoring for now)
- [x] #245
- [x] #239
- [x] #219
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/15
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/16
- [x] [StakingInfo](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/StakingInfo.java)
- [x] #484

**Hbar**

- [x] #552
- [x] [HbarAllowance](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/HbarAllowance.java)
- [x] #553

**Smart Contracts**
- [x] #247
- [x] #252
- [x] #338
- [x] #249
- [x] #270
- [x] #269
- [x] #276
- [x] [ContractFunctionResult](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/ContractFunctionResult.java)
- [x] [ContractFunctionSelector](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/ContractFunctionSelector.java)
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/19
- [x] [ContractId](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/ContractId.java)
- [x] [ContractInfo](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/ContractInfo.java)
- [x] #292
- [x] [ContractLogInfo](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/ContractLogInfo.java)
- [x] [ContractStateChange](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/ContractStateChange.java) (deprecated, will not do)
- [x] #295
- [x] #343
- [x] #346
- [x] #298
- [x] #300
- [x] [EthereumTransactionDataEip1559](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/EthereumTransactionDataEip1559.java)
- [x] [EthereumTransactionDataLegacy](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/EthereumTransactionDataLegacy.java)
- [x] [EvmAddress](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/EvmAddress.java)

**Files**

- [x] #333
- [x] #322
- [x] #273
- [x] #290
- [x] [FileId.java](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/FileId.java)
- [x] [FileInfo](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/FileInfo.java)
- [x] #304
- [x] #318

**Tokens**

- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/199
- [x] #354
- [x] #357
- [x] #356
- [x] #360
- [x] #364
- [x] [NftId](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/NftId.java)
- [x] #415
- [x] #377
- [x] #378
- [x] #390
- [x] #348
- [x] #376
- [x] #389
- [x] #388
- [x] #387
- [x] #386
- [x] [TokenId](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/TokenId.java)
- [x] [TokenInfo](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/TokenInfo.java)
- [x] #401
- [x] #380
- [x] #417
- [x] [TokenNftInfo](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/TokenNftInfo.java)
- [x] #412
- [x] [TokenNftTransfer](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/TokenNftTransfer.java)
- [x] #385
- [x] [TokenRelationship](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/TokenRelationship.java) (use is deprecated, will not do)
- [x] #384
- [x] #352
- [x] #419
- [x] #350
- [x] #381
- [x] #382
- [x] #379
- [x] #383

**Topics**

- [x] #332
- [x] #421
- [x] #426
- [x] #427
- [x] [TopicInfo](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/TopicInfo.java)
- [x] #428
- [x] [TopicMessage](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/TopicMessage.java)
- [x] [TopicMessageChunk](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/TopicMessageChunk.java)
- [x] #431
- [x] #429
- [x] #430

**Schedules**

- [x] #451
- [x] #457
- [x] #455
- [x] [ScheduleInfo](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/ScheduleInfo.java)
- [x] #459
- [x] #464

**Transactions**
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/205
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/14
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/13
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/20
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/56
- [x] #473
- [x] [FreezeType](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/FreezeType.java)
- [x] [HederaPreCheckStatusException](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/HederaPreCheckStatusException.java)
- [x] [HederaReceiptStatusException](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/HederaReceiptStatusException.java)
- [x] [Transaction.java](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/Transaction.java)
- [x] [TransactionFeeSchedule](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionFeeSchedule.java)
- [x] #326
- [x] #328
- [x] #327
- [x] #329
- [x] #330

**Queries**

- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/9
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/11
- [x] #331

**Client**

- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/7
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/217
- [x] [BaseNode](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/BaseNode.java)
- [x] [BaseNodeAddress](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/BaseNodeAddress.java)
- [x] [Executable.java](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/Executable.java)
- [x] [ExecutionState.java](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/ExecutionState.java) (included as a `protected enum` in `Executable`).
- [x] [IPv4Address](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/IPv4Address.java)
- [x] [IPv4AddressPart](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/IPv4AddressPart.java) (internal class, did not implement)
- [x] [MaxAttemptsExceededException](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/MaxAttemptsExceededException.java)
- [x] [MaxQueryPaymentExceededException.java](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/MaxQueryPaymentExceededException.java)
- [x] [MirrorNetwork](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNetwork.java)
- [x] [MirrorNode](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNode.java)
- [x] [NetworkName](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/NetworkName.java) (deprecated, will not do)
- [x] [NetworkVersionInfo](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/NetworkVersionInfo.java)
- [x] #479
- [x] [Node](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/Node.java)
- [x] [NodeAddressBook](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/NodeAddressBook.java)
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/201

**Cryptography/Keys**

- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/29
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/43
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/53
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/122
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/124
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/128
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/129
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/211
- [x] #310
- [x] #312

**Fees**

- [x] [ExchangeRate](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/ExchangeRate.java)
- [x] [ExchangeRates](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/ExchangeRates.java)
- [x] #361
- [x] [FeeComponents](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/FeeComponents.java)
- [x] [FeeData](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/FeeData.java)
- [x] [FeeDataType](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/FeeDataType.java)
- [x] [FeeSchedule](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/FeeSchedule.java)
- [x] [FeeSchedules](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/FeeSchedules.java)
- [x] #393

**Other**

- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/21
- [x] #475
- [x] #476

**Examples**

- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/25
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/95
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/96
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/97
- [x] #486
- [x] [AccountAllowanceExample](https://github.com/hashgraph/hedera-sdk-java/blob/develop/examples/src/main/java/AccountAllowanceExample.java)
- [x] #488
- [x] #492
- [x] #494
- [x] #496
- [x] [ConsensusPubSubExample](https://github.com/hashgraph/hedera-sdk-java/blob/develop/examples/src/main/java/ConsensusPubSubExample.java)
- [x] #519
- [x] #521
- [x] [ContractHelper](https://github.com/hashgraph/hedera-sdk-java/blob/develop/examples/src/main/java/ContractHelper.java)
- [x] #524
- [x] #527
- [x] #280
- [x] [CreateStatefulContractExample](https://github.com/hashgraph/hedera-sdk-java/blob/develop/examples/src/main/java/CreateStatefulContractExample.java)
- [x] #528
- [x] [CustomFeesExample](https://github.com/hashgraph/hedera-sdk-java/blob/develop/examples/src/main/java/CustomFeesExample.java)
- [x] [DeleteAccountExample](https://github.com/hashgraph/hedera-sdk-java/blob/develop/examples/src/main/java/DeleteAccountExample.java)
- [x] [DeleteFileExample](https://github.com/hashgraph/hedera-sdk-java/blob/develop/examples/src/main/java/DeleteFileExample.java)
- [x] [ExemptCustomFeesExample](https://github.com/hashgraph/hedera-sdk-java/blob/develop/examples/src/main/java/ExemptCustomFeesExample.java)
- [x] [FileAppendChunkedExample](https://github.com/hashgraph/hedera-sdk-java/blob/develop/examples/src/main/java/FileAppendChunkedExample.java)
- [x] #531
- [x] [GenerateKeyWithMnemonicExample](https://github.com/hashgraph/hedera-sdk-java/blob/develop/examples/src/main/java/GenerateKeyWithMnemonicExample.java)
- [x] [GetAccountBalanceExample.java](https://github.com/hashgraph/hedera-sdk-java/blob/develop/examples/src/main/java/GetAccountBalanceExample.java)
- [x] #533
- [x] #504
- [x] #535
- [x] [GetFileContentsExample](https://github.com/hashgraph/hedera-sdk-java/blob/develop/examples/src/main/java/GetFileContentsExample.java)
- [x] #538
- [x] #540
- [x] [NftAddRemoveAllowancesExample](https://github.com/hashgraph/hedera-sdk-java/blob/develop/examples/src/main/java/NftAddRemoveAllowancesExample.java)
- [x] #543
- [x] [ScheduleExample](https://github.com/hashgraph/hedera-sdk-java/blob/develop/examples/src/main/java/ScheduleExample.java)
- [x] [ScheduleIdenticalTransactionExample](https://github.com/hashgraph/hedera-sdk-java/blob/develop/examples/src/main/java/ScheduleIdenticalTransactionExample.java)
- [x] [ScheduleMultiSigTransactionExample](https://github.com/hashgraph/hedera-sdk-java/blob/develop/examples/src/main/java/ScheduleMultiSigTransactionExample.java)
- [x] [ScheduledTransactionMultiSigThresholdExample](https://github.com/hashgraph/hedera-sdk-java/blob/develop/examples/src/main/java/ScheduledTransactionMultiSigThresholdExample.java)
- [x] [ScheduledTransferExample](https://github.com/hashgraph/hedera-sdk-java/blob/develop/examples/src/main/java/ScheduledTransferExample.java)
- [x] #545
- [x] #551
- [x] [StakingExample](https://github.com/hashgraph/hedera-sdk-java/blob/develop/examples/src/main/java/StakingExample.java)
- [x] #557
- [x] #559
- [x] [TransferTokensExample](https://github.com/hashgraph/hedera-sdk-java/blob/develop/examples/src/main/java/TransferTokensExample.java)
- [x] #561
- [x] [UpdateAccountPublicKeyExample](https://github.com/hashgraph/hedera-sdk-java/blob/develop/examples/src/main/java/UpdateAccountPublicKeyExample.java)
- [x] #514
- [x] #563

**Comment by SimiHunjan** [comment]
added to list

**Comment by deyanzz** [comment]
[NodeAddress.h](https://github.com/hashgraph/hedera-sdk-cpp/blob/main/sdk/main/include/impl/NodeAddress.h) & [NodeAddress.cc](https://github.com/hashgraph/hedera-sdk-cpp/blob/main/sdk/main/src/impl/NodeAddress.cc) now have a complete implementation merged in `main` branch (done in [Issue #217](https://github.com/hashgraph/hedera-sdk-cpp/issues/217)).

`NodeAddress` version in the `C++ SDK` isn't following exactly the implementation of `BaseNodeAddress` in `Java SDK`, but at this moment it's not so critical.

**Comment by rwalworth** [comment]
@SimiHunjan are we good to close this since all tasks are completed?

**Comment by rwalworth** [comment]
> @rwalworth I'm guessing we can close this? All tasks seem complete. If any follow-up is needed I'm guessing it would be a new issue.

Yep I'd agree, closing now.
