### ISSUE TITLE
Create tests for implemented transactions

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-sdk-cpp#31]
- [x] #32
- [x] #75
- [x] #76
- [x] #77
- [x] #78
- [x] #79
- [x] #80
- [x] #81
- [x] #82
- [x] #83
- [x] #84
- [x] #85
- [x] #86
- [x] #87
- [x] #88
- [x] #89
- [x] #90

**Comment by rwalworth** [comment]
All unit tests created and merged. Closing this issue.
