### ISSUE TITLE
`TransactionResponse` - add member variable `mTransactionHash`

### ISSUE THREAD

**Issue by deyanzz** [hashgraph/hedera-sdk-cpp#313]
### Problem

In Java implementation for [TransactionResponse.java](https://github.com/hashgraph/hedera-sdk-java/blob/develop/sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionResponse.java) could be found a field named `transactionHash`. Currently this field is missing for the C++ implementation of `TransactionResponse`.

### Solution

To add the missing field `mTransactionHash` in `TransactionResponse`

### Alternatives

N/A

**Comment by rwalworth** [comment]
This field was added in #581. Closing.
