### ISSUE TITLE
Full implementation for `TokenNftInfoQuery`

### ISSUE THREAD

**Issue by deyanzz** [hashgraph/hedera-sdk-cpp#437]
### Problem

Class `TokenNftInfoQuery` is missing some member variables:

- `mTokenId`
- `mAccountId`
- `mStart`
- `mEnd`

### Solution

To add all of the missing member variables and functions

For reference see `TokenNftInfoQuery` in the [Java SDK](https://github.com/hashgraph/hedera-sdk-java).

### Alternatives

N/A

**Comment by rwalworth** [comment]
Those fields are only used in deprecated functions, we don't have to implement them. Unless I'm missing something?

**Comment by rwalworth** [comment]
@deyanzz do you have any objection to closing this?
