### ISSUE TITLE
AccountId#toSolidityAddress() does not return expected result when AccountId has a Key Alias

### ISSUE THREAD

**Issue by svetoslav-nikol0v** [hashgraph/hedera-sdk-cpp#498]
### Problem

 ```
const createAccountTxRecordWithChildren = await new TransactionRecordQuery()
        .setTransactionId(createAccountTxRecord.transactionId)
        .setIncludeChildren(true)
        .execute(client);
    const multisigAccountId =
        createAccountTxRecordWithChildren?.children[0]?.receipt?.accountId;
    const multisigAccountEvmAddress =
        createAccountTxRecordWithChildren?.children[0]?.evmAddress;
    console.log('multisigAccountId', multisigAccountId.toString());
    console.log('multisigAccountEvmAddress', multisigAccountEvmAddress.toString());
    console.log('toLongZeroEvmAddress(multisigAccountId)', toLongZeroEvmAddress(multisigAccountId));
    console.log('multisigAccountId.toSolidityAddress()', multisigAccountId.toSolidityAddress());
```

```
multisigAccountId 0.0.630405
multisigAccountEvmAddress 6c48bca69c6e7ebcc565f4b79d890eb1fe45e07f
toLongZeroEvmAddress(multisigAccountId) 0000000000000000000000000000000000099e85
multisigAccountId.toSolidityAddress() 0000000000000000000000000000000000099e85
```

### Solution

- In this scenario I expect multisigAccountEvmAddress and multisigAccountId.toSolidityAddress() to be the same - the "regular" EVM address
- And expect only toLongZeroEvmAddress(multisigAccountId) (which is EntityIdHelper.toSolidityAddress([shard, realm, num])) to give me the long zero address

### Alternatives

[Link to issue in JS SDK](https://github.com/hashgraph/hedera-sdk-js/issues/1817).

**Comment by gsstoykov** [comment]
The fix implementation is dependant on having a proper channel from which the ```MirrorNode``` can be queried. I checked the linked issue from the JS SDK which brings the attention to creating a function ```populateAccountEvmAddress```. The function goal is fetching the missing ```EvmAddress``` data from the ```MirrorNode```. In the C++ SDK we can try to get the instance of the ```MirrorNode``` but the get call results in a segmentation fault coming from a call to ```std::unique_lock lock(*getLock());``` this arises concerns for bad synchronization in the internal state of the ```MirrorNode```. Should be further analysed.

**Comment by gsstoykov** [comment]
Further analysed the possible synchronization issue. Turns out the problem coming from the ```getLock()``` function which gets a mutex from the ```MirrorNetwork``` instance is due to bad class initialisation. The ```Client``` class handles the ```MirrorNetwork``` init logic via setting a defaut testnet url. But the ```networkMap``` is initialised in a bad manner further leading to ```MirrorNetwork``` not being initialised correctly and then bad calls to getLock() function.

**Comment by gsstoykov** [comment]
Above comments are now obsolete. For task continuation https://github.com/hashgraph/hedera-sdk-cpp/issues/547 should be implemented.
