### ISSUE TITLE
"segmentation fault" after updating from v0.18 to v0.19

### ISSUE THREAD

**Issue by Dubiy** [hashgraph/hedera-sdk-cpp#583]
### Description

After updating from v0.18 to v0.19 got `segmentation fault` on executing any transaction.

Changes of updating to v0.19 - https://github.com/Blade-Labs/cpp-blade-demoapp/commit/75f552aa542b4df056378e13ac2f6e3cadb0f7d6

code example:
```
std::string accountId = "0.0.346533";
std::string accountPrivateKey = "3030020100300706052b8104000a04220420ebccecef769bb5597d0009123a0fd96d2cdbe041c2a2da937aaf8bdc8731799b";
std::string recieverAccount = "0.0.346530";
std::string amount = "15";
std::string memo = "cpp-sdk-test";

Client client = this->getClient();
client.setOperator(AccountId::fromString(accountId), ECDSAsecp256k1PrivateKey::fromString(accountPrivateKey));
const Hbar amountHbar(std::stoull(amount), HbarUnit::HBAR());

TransactionResponse txResponse = TransferTransaction()
                                .addHbarTransfer(AccountId::fromString(accountId), amountHbar.negated())
                                .addHbarTransfer(AccountId::fromString(recieverAccount), amountHbar)
                                .setTransactionMemo(memo)
                                .execute(client);

TransactionReceipt receipt = txResponse.getReceipt(client);
```

### Steps to reproduce

1. git clone https://github.com/Blade-Labs/cpp-blade-demoapp
2. cd cpp-blade-demoapp
3. git submodule update --init
4. cmake --preset macos-arm64-release
5. cmake --build --preset macos-arm64-release
6. cd package/bin && ./demo-application

### Additional context

```
gary@du cpp-blade-demoapp % cmake --build --preset macos-arm64-release && cd package/bin && ./demo-application
[0/1] Install the project...
-- Install configuration: "Release"
-- Installing: /Users/gary/dev/cpp/cpp-blade-demoapp/package/lib/libblade-cpp.a
-- Up-to-date: /Users/gary/dev/cpp/cpp-blade-demoapp/package/bin/demo-application
Demo application using BladeSDK
init: {dAppCode: "unitysdktest", network: "TESTNET", apiKey: GgsRv5PWfQaRQkykgSDRR3JzXN6kVRwv8RWGIes6SnH2vbSnxWMrf5AAxGbQdYbv, visitorId: 26b127c2fb4cf57625a3ae627ac903e4c2e0b604e6863632122cb15615c844ed, sdkEnvironment: "CI", sdkVersion: Cpp@0.6.4}
zsh: segmentation fault  ./demo-application
gary@du bin %
```

### Hedera network

testnet

### Version

v0.19

### Operating system

macOS

**Comment by rwalworth** [comment]
Hi @Dubiy, I'm having some trouble reproducing this using the steps you provided. I'm not even getting to the `init: {dAppCode:...` line and getting either a `zsh: segmentation fault ./demo-application` or `zsh: trace trap ./demo-application` error. I traced this to in your `Blade::Blade` constructor and it looks like the line `this->visitorId = fingerprintService.getVisitorId()` is the culprit. I tried commenting it out but am running into more errors. You have any suggestions here on how I can reproduce this?

As a note, I did copy-paste the code you posted into a separate executable (replacing `this->getClient()` with just `Client::forTestnet()`) and was able to run it fine.

**Comment by Dubiy** [comment]
try to comment `// FingerprintService fingerprintService = FingerprintService();`, and set `this->visitorId` any string, like this:

```
  Blade::Blade(const std::string& apiKey, const Network& network, const std::string& dAppCode, const SdkEnvironment& sdkEnvironment)
    : apiService(apiKey, network, dAppCode, sdkEnvironment)
  {
    this->network = network;
    this->apiKey = apiKey;
    this->dAppCode = dAppCode;
    this->sdkEnvironment = sdkEnvironment;
    // FingerprintService fingerprintService = FingerprintService();
    this->visitorId = "fake-visitor-id";
    apiService.init(this->sdkVersion, this->visitorId);
  }
```

Output:
```
Demo application using BladeSDK
init: {dAppCode: "unitysdktest", network: "TESTNET", apiKey: GgsRv5PWfQaRQkykgSDRR3JzXN6kVRwv8RWGIes6SnH2vbSnxWMrf5AAxGbQdYbv, visitorId: fake-visitor-id, sdkEnvironment: "CI", sdkVersion: Cpp@0.6.4}
zsh: segmentation fault  ./demo-application
gary@du bin %
```

**Comment by rwalworth** [comment]
Figured out the issue. The location to which you were installing the address books was incorrect and thus the `Client` network wasn't being initialized properly. In your `CMakeLists.txt`, I was able to replace the

`file(COPY ${CMAKE_SOURCE_DIR}/libraries/blade-cpp/assets/mainnet.pb DESTINATION ${CMAKE_SOURCE_DIR}/package/bin)`
`file(COPY ${CMAKE_SOURCE_DIR}/libraries/blade-cpp/assets/previewnet.pb DESTINATION ${CMAKE_SOURCE_DIR}/package/bin)`
`file(COPY ${CMAKE_SOURCE_DIR}/libraries/blade-cpp/assets/testnet.pb DESTINATION ${CMAKE_SOURCE_DIR}/package/bin)`

lines with

`install(FILES`
`        ${CMAKE_SOURCE_DIR}/libraries/blade-cpp/assets/mainnet.pb`
`        ${CMAKE_SOURCE_DIR}/libraries/blade-cpp/assets/previewnet.pb`
`        ${CMAKE_SOURCE_DIR}/libraries/blade-cpp/assets/testnet.pb`
`        DESTINATION bin/addressbook)`
        
and get it to work. The SDK accesses address book protobuf and JSON config files in matching `addressbook` and `config` directories that must be in the same directory as the executable. This isn't written anywhere in documentation so I'll be sure to add it. But feel free to try this change and let me know if there's anymore issue!
