### ISSUE TITLE
Get account token balances

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-cpp#587]
### Problem

Accounts hold hbar balances and HTS token balances. The token balance information was deprecated for the Hedera APIs (protobuf), but we should still supply a way to get the token balances for a specified account. This can be achieved by using the Mirror Node Rest API: 
- https://mainnet-public.mirrornode.hedera.com/api/v1/docs/#/accounts/listTokenRelationshipByAccountId

Support for hbar balance that exists today:

```
//Account Hbar Balances
 Hbar balance = AccountBalanceQuery().setAccountId(accountId).execute(client).getBalance();
```

### Solution

Add support to query token balances for a given account via the mirror node rest API. 

- [ ] Document the intended design to support this feature
- [ ] Implement the feature
- [ ] Add example to demonstrate the use of the feature

**Comment by rwalworth** [comment]
Is this something that is available in other SDKs? Just curious, I don't believe I see anything in them that uses a mirror node query to get this information; it looks like they still primarily use the `AccountBalance` object, but maybe I just can't find it.

**Comment by SimiHunjan** [comment]
No it is not yet. This issue is related to this https://www.notion.so/swirldslabs/Add-Token-Balances-Query-bf1ed356a1d54303b370ea1d6a90d053. 

Previously we had the following in other SDKs, but it is now marked as deprecated:
https://github.com/hashgraph/hedera-sdk-js/blob/develop/src/account/AccountBalance.js#L62

I created the issue just to note that this is a gap we know about and will plan to add support for. 

We need to come up with a design that all SDKs would then follow and implement in a future sprint.

**Comment by gsstoykov** [comment]
Just noticed that I have created a duplication here: https://github.com/hashgraph/hedera-sdk-cpp/issues/637. Will close this issue when 637 is resolved!
