### ISSUE TITLE
Possible inconsistency between ED keys produced with other SDKs

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-cpp#590]
### Problem

The generated private keys for the same function in the Java/JS/etc SDKs produce different outputs.

The generated ED private keys in the C++ SDK are as follow:

C++
```
  // Generate a ED25519 private, public key pair
  const std::unique_ptr<PrivateKey> privateKey = ED25519PrivateKey::generatePrivateKey();
  const std::shared_ptr<PublicKey> publicKey = privateKey->getPublicKey();

  std::cout << "Generated private key: " << privateKey->toStringRaw() << std::endl;
  std::cout << "Generated public key: " << publicKey->toStringRaw() << std::endl;

  std::cout << "Generated private key: " << privateKey << std::endl;
  std::cout << "Generated public key: " << publicKey << std::endl;
```
```
//Raw format without the prefix
Generated private key: 82F8B669C00FEABC4C78EAA7D9C048FC1AE7ECB71A93BB928D99B7E3C7DD32A3
Generated public key: E6C8B6A456C4EF44E384E5C5F38EE04E936D680CAA54BC3CBCBF0430934593BA

//Not sure what this is printing? I would expect if I am just using privateKey and publicKey it would show the same format as the other SDKs. I could be missing something so please let me know in the comments.

Generated private key: 0x600003348280
Generated public key: 0x60000314b3e0
```

Java:
```
        // Generate a new key pair
        PrivateKey newAccountPrivateKey = PrivateKey.generateED25519();
        PublicKey newAccountPublicKey = newAccountPrivateKey.getPublicKey();
        
        System.out.println("The ED25519 private key" + newAccountPrivateKey);
        System.out.println("The ED25519 public key" + newAccountPublicKey);
```

Keys Generated:

```
The ED25519 private key 302e020100300506032b6570042204204bf70101bf54b418c28c9f81f7207514f454994a1a9c2f9cd46d5279b8d930d1
The ED25519 public key 302a300506032b65700321003683a8d7122bd8e4e679208f14a526e44a9039bf651bd35d0c216848bd272143
```

JavaScript:

```
const newPrivateKey = PrivateKey.generateED25519()
const newPublicKey = newPrivateKey.publicKey
```

Key Generated:
```
The ED private key is 302e020100300506032b657004220420fadd30cacabe35a35bf3400394685965d8ef23a62d2d3ee47fa8974b31f6107e
The ED public key is 302a300506032b6570032100767495272ca013820b307b2c5d4558e6204b7063edef442501281e42ead225f5
```

### Solution

TBD

**Comment by rwalworth** [comment]
> ### Problem
> The generated private keys for the same function in the Java/JS/etc SDKs produce different outputs.
> 
> The generated ED private keys in the C++ SDK are as follow:
> 
> C++
> 
> ```
>   // Generate a ED25519 private, public key pair
>   const std::unique_ptr<PrivateKey> privateKey = ED25519PrivateKey::generatePrivateKey();
>   const std::shared_ptr<PublicKey> publicKey = privateKey->getPublicKey();
> 
>   std::cout << "Generated private key: " << privateKey->toStringRaw() << std::endl;
>   std::cout << "Generated public key: " << publicKey->toStringRaw() << std::endl;
> 
>   std::cout << "Generated private key: " << privateKey << std::endl;
>   std::cout << "Generated public key: " << publicKey << std::endl;
> ```
> 
> ```
> //Raw format without the prefix
> Generated private key: 82F8B669C00FEABC4C78EAA7D9C048FC1AE7ECB71A93BB928D99B7E3C7DD32A3
> Generated public key: E6C8B6A456C4EF44E384E5C5F38EE04E936D680CAA54BC3CBCBF0430934593BA
> 
> //Not sure what this is printing? I would expect if I am just using privateKey and publicKey it would show the same format as the other SDKs. I could be missing something so please let me know in the comments.
> 
> Generated private key: 0x600003348280
> Generated public key: 0x60000314b3e0
> ```
> 
> Java:
> 
> ```
>         // Generate a new key pair
>         PrivateKey newAccountPrivateKey = PrivateKey.generateED25519();
>         PublicKey newAccountPublicKey = newAccountPrivateKey.getPublicKey();
>         
>         System.out.println("The ED25519 private key" + newAccountPrivateKey);
>         System.out.println("The ED25519 public key" + newAccountPublicKey);
> ```
> 
> Keys Generated:
> 
> ```
> The ED25519 private key 302e020100300506032b6570042204204bf70101bf54b418c28c9f81f7207514f454994a1a9c2f9cd46d5279b8d930d1
> The ED25519 public key 302a300506032b65700321003683a8d7122bd8e4e679208f14a526e44a9039bf651bd35d0c216848bd272143
> ```
> 
> JavaScript:
> 
> ```
> const newPrivateKey = PrivateKey.generateED25519()
> const newPublicKey = newPrivateKey.publicKey
> ```
> 
> Key Generated:
> 
> ```
> The ED private key is 302e020100300506032b657004220420fadd30cacabe35a35bf3400394685965d8ef23a62d2d3ee47fa8974b31f6107e
> The ED public key is 302a300506032b6570032100767495272ca013820b307b2c5d4558e6204b7063edef442501281e42ead225f5
> ```
> 
> ### Solution
> TBD
> 
> ### Alternatives
> _No response_

That is the printout of the byte address of the `PrivateKey`. There's no way to replicate the other SDKs perfect, but I should be able to do something like `std::cout << *privateKey << std::endl;`, which can print out the DER-encoded hex string of the key. Will that suffice for this?

**Comment by SimiHunjan** [comment]
Are there cases where the developer would use the byte address for anything? My line of thought is a wallet app wants to display the private key to the user. If the developer called `privateKey` alone it would display the byte address to the user. I saw do have a way to take the `privateKey` and derive a DER-encoded hex string like this:

`std::cout << "Generated ED25519PublicKey DER encoded: " << ed25519Key->getPublicKey()->toStringDer() << std::endl;`

Curious if the byte address output is something that is ever used. 

The above solution sounds good.

**Comment by rwalworth** [comment]
Most likely the byte address would not be useful to the user as it simply states where the `std::shared_ptr<PrivateKey>` object lives in memory. I will start working on the solution mentioned above.
