### ISSUE TITLE
QA APIs/Examples

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-cpp#591]
When the development work for the features are complete in the SDK, the features need to go through a QA process to ensure the implementation of the feature works as expected and is similar to the other SDKs from a user perspective. 

**Recovery Phrase and Key Generation**
- [x] #594
- [x] #595
- [x] #599
- [x] QA: Generate ECDSA recovery phrase
- [x] #604

**Client**
- [x] QA: Create a client for all supported networks

**Accounts**
- [x] #600
- [x] #601
- [x] #622
- [x] #626
- [x] QA: Transfer hbars between two accounts
- [x] QA: Transfer HTS tokens between to accounts
- [x] #603
- [x] #621
- [x] Get account balance (hbars)

**Smart Contracts**
- [x] QA: Create a smart contract
- [x] QA: Update a smart contract
- [x] QA: Delete a smart contract
- [x] QA: Call a function of the smart contract

**Tokens**
- [x] #630
- [x] #623
- [x] QA: Update a token
- [x] #624
- [x] QA: Delete a token
- [x] QA: Freeze a token
- [x] #625

**Topics** 
- [x] #627
- [x] QA: Update a topic
- [x] QA: Delete a topic
- [x] #628

**Files**
- [x] QA: Create a file
- [x] QA: Update a file
- [x] #629
- [x] QA: Query a file

**Schedules**

**Transactions**
- [x] Modify transaction properties 

**Queries**
- [x] Modify query properties 

**Node Selection**

**Issues:**

- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/590
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/593
- [x] https://github.com/hashgraph/hedera-sdk-cpp/issues/596

**Comment by gsstoykov** [comment]
QA: Transfer HTS tokens between to accounts - https://github.com/hashgraph/hedera-sdk-cpp/blob/4b2151014428c0721955fbbef2793818465629d6/src/sdk/examples/TransferTokensExample.cc#L4
QA: Transfer hbars between two accounts - https://github.com/hashgraph/hedera-sdk-cpp/blob/4b2151014428c0721955fbbef2793818465629d6/src/sdk/examples/TransferCryptoExample.cc#L4
QA: Create a smart contract
QA: Delete a smart contract
QA: Call a function of the smart contract - https://github.com/hashgraph/hedera-sdk-cpp/blob/4b2151014428c0721955fbbef2793818465629d6/src/sdk/examples/ContractNoncesExample.cc#L4
QA: Update a token - https://github.com/hashgraph/hedera-sdk-cpp/blob/4b2151014428c0721955fbbef2793818465629d6/src/sdk/examples/TokenMetadataExample.cc#L4
QA: Update a topic - https://github.com/hashgraph/hedera-sdk-cpp/blob/4b2151014428c0721955fbbef2793818465629d6/src/sdk/examples/TopicWithAdminKeyExample.cc#L4
QA: Create a file - https://github.com/hashgraph/hedera-sdk-cpp/blob/4b2151014428c0721955fbbef2793818465629d6/src/sdk/examples/DeleteFileExample.cc#L4

I am going to assume these examples verify the flows mentioned in the epic. Some of these examples are new and I am updating the above list with the latest verified.

**Comment by gsstoykov** [comment]
QA: Create a client for all supported networks - https://github.com/hashgraph/hedera-sdk-cpp/blob/4cbab2f6401ee18227b32f0ca44cb1b0c1e20aab/src/sdk/examples/ConstructClientExample.cc
Also could be marked ready.
Transactions, Queries(sections) could also be closed. Was this intended to be further edited?  Modifying transaction, query properties is demonstrated throughout all of the examples.

**Comment by gsstoykov** [comment]
Overall I think the 
```
Transactions
* Modify transaction properties
Queries
* Modify query properties
```
Sections are good to be closed or redundant. We have multiple examples demonstrating the altering of transaction/query props. There are even examples modifying some core transaction functionalities like `maxTransactionFee` (AccountCreateWithHtsExample.cc, ContractNoncesExample.cc, CreateSimpleContractExample.cc and others). Should we define some specific issue regarding the above topic or the sections are good to be closed(WDYT @rwalworth )

**Comment by rwalworth** [comment]
> Overall I think the
> 
> ```
> Transactions
> * Modify transaction properties
> Queries
> * Modify query properties
> ```
> 
> Sections are good to be closed or redundant. We have multiple examples demonstrating the altering of transaction/query props. There are even examples modifying some core transaction functionalities like `maxTransactionFee` (AccountCreateWithHtsExample.cc, ContractNoncesExample.cc, CreateSimpleContractExample.cc and others). Should we define some specific issue regarding the above topic or the sections are good to be closed(WDYT @rwalworth )

I'm good to close since we have examples already that show this.
