### ISSUE TITLE
QA: Generate ED25519 recovery phrase

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-cpp#599]
Generate a recovery phrase that results in deriving ED25519 key types.

- [x] Generate a 12 word recovery phrase
- [x] Generate a 24 word recovery phrase
- [ ] Generate a private key from the 12 word recovery phrase
- [ ] Generate a private key from the 24 word recovery phrase
- [ ] Use the 12 word recovery phrase to regenerate a key
- [ ] Use the 24 word recovery phrase to regenerate a key

**Comment by SimiHunjan** [comment]
I am little unclear on the mnemonic feature we have support for (in general as this question is applicable to all SDKs). I can see we support 12 and 24 word mnemonic phrase generation. Initially we only supported ED25519 keys so it was obvious the recovery phrase feature would generate a recovery phrase and then you could generate an associated ED25519 key. Now we support both ED25519 and ECSDA. What I am unclear on is when I use:
  
```
const MnemonicBIP39 mmneumonic = MnemonicBIP39::generate12WordBIP39Mnemonic();
std::cout << "Generate a 12 word recovery phrase: " << mmneumonic.toString() << std::endl;
```

How do I know which key type this mnemonic is going to generate keys for? Or do I specify that after I create the mnemonic/recovery phrase? I know that for ED key generation there is an index for every key and if you want to regenerate keys from a recovery phrase you have to also provide the index. Also is the above code snippet correct in what I am trying to achieve.

**Comment by SimiHunjan** [comment]
### Code Example

```
  // Generate a ED25519 recovery phrase
  const MnemonicBIP39 mneumonic1 = MnemonicBIP39::generate12WordBIP39Mnemonic();

  std::cout << "Generated a 12 word recovery phrase: " << mneumonic1.toString() << std::endl;

  const MnemonicBIP39 mneumonic2 = MnemonicBIP39::generate24WordBIP39Mnemonic();
  std::cout << "Generated a 24 word recovery phrase: " << mneumonic2.toString() << std::endl;
```

### Output

**Comment by rwalworth** [comment]
One mnemonic can generate `ED25519` and `ECDSAsecp256k1` keys; mnemonics aren't specific to one type of key. In the `MnemonicBIP39` object, there are `toStandardEd25519PrivateKey` and `toStandardECDSAsecp256k1PrivateKey` functions that can generate these private keys.

**Comment by SimiHunjan** [comment]
### :white_check_mark: Test C++ SDK Recovery Phrase and Key Generation Compatibility with Java SDK

```Java
package org.example;

import com.hedera.hashgraph.sdk.*;
public class MneumonicExample {

    public static void main(String[] args) throws BadMnemonicException {

        //This 12 word recovery phrase string was generated from the c++ sdk
        Mnemonic mnemonic1 = Mnemonic.fromString("soccer loan bomb yard accuse doctor man mean lawn wing swift bread");

        //The private key at index 0 generated by the c++ SDK
        PrivateKey cppPrivateKey0 = PrivateKey.fromString("302E020100300506032B657004220420BA36ED3F60E3DA30B5DB6215461FAFFC2FCD066F385FD2261F74AB4E174E4591");

        //Generate ED25519 private key at index 0
        PrivateKey privateKey0 = mnemonic1.toStandardEd25519PrivateKey("",0);

        System.out.println("PrivateKey0 (c++): " + cppPrivateKey0);
        System.out.println("PrivateKey0 (jav): " + privateKey0);

    }
}
```
### Output

```
PrivateKey0 (c++): 302e020100300506032b657004220420ba36ed3f60e3da30b5db6215461faffc2fcd066f385fd2261f74ab4e174e4591
PrivateKey0 (jav): 302e020100300506032b657004220420ba36ed3f60e3da30b5db6215461faffc2fcd066f385fd2261f74ab4e174e4591
```
