### ISSUE TITLE
QA: Delete a file

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-cpp#629]
Delete a file and its state from consensus nodes.

**Comment by SimiHunjan** [comment]
### Code Example
```
#include "Client.h"
#include "ED25519PrivateKey.h"
#include "FileCreateTransaction.h"
#include "FileDeleteTransaction.h"
#include "FileId.h"
#include "Status.h"
#include "TransactionReceipt.h"
#include "TransactionResponse.h"
#include "impl/Utilities.h"
#include "FileInfo.h"
#include "FileInfoQuery.h"
#include <iostream>

using namespace Hedera;


int main(int argc, char** argv)
{
  if (argc < 3)
  {
    std::cout << "Please input account ID and private key" << std::endl;
    return 1;
  }

  // Get a client for the Hedera testnet, and set the operator account ID and key such that all generated transactions
  // will be paid for by this account and be signed by this key.
  Client client = Client::forTestnet();
  client.setOperator(AccountId::fromString(argv[1]), ED25519PrivateKey::fromString(argv[2]));

  // Create a new file.
  const FileId fileId = FileCreateTransaction()
                          .setKeys({ client.getOperatorPublicKey() })
                          .setContents(internal::Utilities::stringToByteVector("Hedera Hashgraph is great!"))
                          .execute(client)
                          .getReceipt(client)
                          .mFileId.value();
  std::cout << "Created new file with ID " << fileId.toString() << std::endl;

  // Delete the newly-created file.
  const TransactionReceipt txReceipt = FileDeleteTransaction().setFileId(fileId).execute(client).getReceipt(client);
  std::cout << "Deleted file with response code: " << gStatusToString.at(txReceipt.mStatus) << std::endl;

  const FileInfo getFileInfo = FileInfoQuery()
          .setFileId(fileId)
          .execute(client);

  std::cout << "File is deleted: " << getFileInfo.mIsDeleted << std::endl;

  return 0;
}
```

### Output

```
Created new file with ID 0.0.5996837
Deleted file with response code: SUCCESS
File is deleted: 1
```

**Comment by SimiHunjan** [comment]
Hey @rwalworth !

I added the file info query at the end to validate the state of the file recorded it was deleted.

I am getting the response 1 (`File is deleted: 1`).

I believe this should be returning `true`.

**Comment by rwalworth** [comment]
> Hey @rwalworth !
> 
> I added the file info query at the end to validate the state of the file recorded it was deleted.
> 
> I am getting the response 1 (`File is deleted: 1`).
> 
> I believe this should be returning `true`.

C++ doesn't print booleans as strings unfortunately. Any value over `0` is considered `true`, while `0` is considered `false`.

**Comment by rwalworth** [comment]
> > Hey @rwalworth !
> > I added the file info query at the end to validate the state of the file recorded it was deleted.
> > I am getting the response 1 (`File is deleted: 1`).
> > I believe this should be returning `true`.
> 
> C++ doesn't print booleans as strings unfortunately. Any value over `0` is considered `true`, while `0` is considered `false`.

@SimiHunjan just learned this, if you do
`std::cout << "File is deleted: " << std::boolalpha << getFileInfo.mIsDeleted << std::endl;`
it'll print the `bool` as a string

**Comment by SimiHunjan** [comment]
ah thanks @rwalworth will try this out! Thank you!

**Comment by gsstoykov** [comment]
This could be closed due to having https://github.com/hashgraph/hedera-sdk-cpp/blob/main/src/sdk/examples/DeleteFileExample.cc
