### ISSUE TITLE
Test the performance of retrieving data from the Mirror vs the Consensus nodes

### ISSUE THREAD

**Issue by Petyo-Lukanov** [hashgraph/hedera-sdk-cpp#645]
In relation to - https://github.com/hashgraph/hedera-sdk-cpp/issues/637 - we want to test if there is any significant difference between retrieving token balance data from the Mirror node vs retrieving the same data from the Consensus node.

**Comment by gsstoykov** [comment]
<img width="424" alt="Screenshot 2024-01-11 at 13 52 05" src="https://github.com/hashgraph/hedera-sdk-cpp/assets/146725010/9b2d4794-a212-4544-b34a-1a112d4937b4">
These are the measured times for an account balance query from Mirror and Consensus nodes. The measurement is SDK agnostic it should produce the same results in all the SDKs. The measurement was done on a REST API call for the Mirror Node. For the Consensus Node it is simply a GRPC call to the appropriate endpoint.
