### ISSUE TITLE
Move `OpenSSL` to `vcpkg`

### ISSUE THREAD

**Issue by rwalworth** [hashgraph/hedera-sdk-cpp#646]
With the latest release of [vcpkg](https://github.com/microsoft/vcpkg/releases/tag/2024.01.12), OpenSSL `3.2.0` is supported, which is the same version we use in order to get access to the keccak hash functions needed for the `ECSAsecp256k1` key objects. Using `vcpkg` instead of building separately will help a lot with build times, as well as cutting down on the number of artifacts we need to add to releases.

**Comment by gsstoykov** [comment]
```
-- Running vcpkg install
error: no version database entry for openssl at 3.1.4.
Available versions:
  3.1.3
  3.1.2#3
  3.1.2#2
  3.1.2#1
  3.1.2
  ```
  
Will try this at a later moment moving to backlog!
