### ISSUE TITLE
TCK-CPP: Implement `AccountDeleteTransaction` JSON-RPC Endpoint

### ISSUE THREAD

**Issue by gsstoykov** [hashgraph/hedera-sdk-cpp#668]
### Problem

`AccountDeleteTransaction` test isn't covered by the TCK-CPP server.

### Solution

We should implement JSON-RPC methods (endpoints) for `AccountDeleteTransaction` for the TCK-CPP server.

**Comment by rwalworth** [comment]
Duplicate of #739. Closing
