### ISSUE TITLE
`TCK-CPP`: Implement `AccountUpdateTransaction` JSON-RPC Endpoint

### ISSUE THREAD

**Issue by gsstoykov** [hashgraph/hedera-sdk-cpp#670]
### Problem

`AccountUpdateTransaction`  test isn't covered by the TCK-CPP server.

### Solution

We should implement JSON-RPC methods (endpoints) for `AccountUpdateTransaction`  for the TCK-CPP server.

**Comment by rwalworth** [comment]
Duplicate of #702. Closing
