### ISSUE TITLE
Implement a basic `Query` base class

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-sdk-cpp#9]
Implement a basic query base class, to contain payment and transaction informations for queries.

Include implementations of the following APIs:
`T& setQueryPayment(Hbar queryPayment);`
`T& setMaxQueryPayment(Hbar maxQueryPayment)`

- [x] #17

**Comment by rwalworth** [comment]
Implementation and clean-up of `Query` base class has been done in other issues.
